# xkcd-provider Makefile

CAPABILITY_ID = "wasmcloud:example:xkcd_provider"
NAME = "xkcd-provider"
VENDOR = "Cosmonic"
PROJECT = xkcd_provider
VERSION = 0.1.0
REVISION = 0

include ./provider.mk

test::
	cargo clippy --all-targets --all-features

